#!/usr/bin/env python3
"""Show the correct cell execution order for Option E notebook"""

print("="*60)
print("📋 CORRECT CELL EXECUTION ORDER - Option E")
print("="*60)
print()
print("Before testing, you must run these cells in order:")
print()
print("Setup & Model Loading:")
print("  ✓ Cell 0-2:   Title, Imports")
print("  ✓ Cell 3:     DISEASE_NAMES constant")
print("  ✓ Cell 4:     RealConstrainedLogitsProcessor class")
print("  ✓ Cell 5-8:   Model loading, dataset loading")
print()
print("⚠️  CRITICAL - Initialize Constrained Processor:")
print("  ✓ Cell 9:     constrained_processor = RealConstrainedLogitsProcessor(...)")
print("                ↑ THIS MUST RUN BEFORE TESTING!")
print()
print("Continue setup:")
print("  ✓ Cell 10-15: Data formatting, data collator")
print("  ✓ Cell 16-17: Light weighted sampling")
print("  ✓ Cell 18:    Training config")
print("  ✓ Cell 19:    WeightedSamplerTrainer class")
print("  ✓ Cell 20:    Trainer initialization")
print()
print("Training:")
print("  ✓ Cell 21:    trainer.train()")
print()
print("Testing (after training):")
print("  ✓ Cell 22+:   Test cells (use constrained_processor)")
print()
print("="*60)
print("🔴 YOUR ERROR: Cell 9 was not executed!")
print("="*60)
print()
print("Solution: Run Cell 9 now to create constrained_processor")
print()
